[package]
name = "teo-generator"
version = "0.0.58"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teo-result = "0.0.58"
teo-runtime = { path = "../teo-runtime" }
teo-parser = { path = "../teo-parser" }
async-trait = "0.1.74"
async-recursion = "1.0.5"
inflector-plus = "0.11.7"
pad = "0.1.6"
colored = "2.0.4"
askama = "0.12.1"
pathdiff = "0.2.1"
maplit = "1.0.2"
toml_edit = "0.20.7"
tokio = { version = "1.0", features = ["full"] }
